### ISSUE TITLE
Worldedit Unknown issue - Can't replace more than 16 blocks at a time.

### ISSUE THREAD

**Issue by ZaySaurus** [Uberi/Minetest-WorldEdit#182]
[20:49:24] [Server thread/ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.IBlockState.d()Ljava/util/Collection;
        at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_14_R2.getProperties(Spigot_v1_14_R2.java:406) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitBlockRegistry.getProperties(BukkitBlockRegistry.java:52) ~[?:?]
        at com.sk89q.worldedit.world.block.BlockType.lambda$getPropertyMap$1(BlockType.java:121) ~[?:?]
        at com.sk89q.worldedit.world.block.BlockType.updateField(BlockType.java:74) ~[?:?]
        at com.sk89q.worldedit.world.block.BlockType.getPropertyMap(BlockType.java:120) ~[?:?]
        at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseProperties(DefaultBlockParser.java:171) ~[?:?]
        at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:314) ~[?:?]
        at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:88) ~[?:?]
        at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:61) ~[?:?]
        at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:73) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitAdapter$1.apply(BukkitAdapter.java:391) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitAdapter$1.apply(BukkitAdapter.java:386) ~[?:?]
        at java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:1.8.0_162]
        at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:386) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:416) ~[?:?]
        at com.sk89q.worldedit.EditSession.getBlock(EditSession.java:568) ~[?:?]
        at com.sk89q.worldedit.session.request.RequestExtent.getBlock(RequestExtent.java:80) ~[?:?]
        at com.sk89q.worldedit.function.mask.BlockMask.test(BlockMask.java:99) ~[?:?]
        at com.sk89q.worldedit.function.RegionMaskingFilter.apply(RegionMaskingFilter.java:53) ~[?:?]
        at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:57) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:55) ~[?:?]
        at com.sk89q.worldedit.EditSession.replaceBlocks(EditSession.java:1002) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommands.replace(RegionCommands.java:184) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommandsRegistration._replace(RegionCommandsRegistration.java:429) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:158) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:471) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_162]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:328) ~[?:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:689) ~[craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-9c887d4]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1590) ~[craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-9c887d4]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1444) ~[craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-9c887d4]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(SourceFile:37) ~[craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-9c887d4]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(SourceFile:9) ~[craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-9c887d4]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-9c887d4]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:868) [craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:861) [craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:844) [craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:785) [craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-9c887d4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]

**Comment by sfan5** [comment]
This is not the repository you're looking for.
There's a bug report link for Minecraft WorldEdit on its [Bukkit page](https://dev.bukkit.org/projects/worldedit).
